### ISSUE TITLE
Value of Error Code in FAQ

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fwprofile#1]
This issue was first raised as Mantis 297.

The text in the FAQ refers to "success" as the value of the error code in the absence of any errors. In fact, the value is either "smSuccess" or "prSuccess".

**Comment by oppm** [comment]
Do you want me to move the *.tex and *.sh files also from SVN ?

**Comment by cechticky** [comment]
We were never sure how to handle the official fwprofile documentation on Github. May be it can be migrated to GitBook. But, GitBook doesn't have the same features as Latex. The plan so far was to make the source code under LGPL, but documentation shall be made available as PDF. Still to be discussed.

**Comment by oppm** [comment]
Ok. I keep it as it is for the moment. So tex in SVN, in GitHub only pdf.

**Comment by pasetti** [comment]
Actually, I would be in favour of putting all source files for the documentation on GitHub (**with the exception of the items in the /commercial sub-directory**). The rationale for this decision is:

- All our documents carry a prominent copyright statement 
- We are already making them available as PDF and hence, if someone wanted to steal them, they would already be able to do it
- If we want to move to the GitHub release concept (and I think that we should), then we need all sources to be available on GitHub

**Comment by pasetti** [comment]
The error in the FAQ has been fixed and the change has been pulled into the master branch.
