### ISSUE TITLE
Tests and examples not built / run by Travis

### ISSUE THREAD

**Issue by oppm** [pnp-software/fwprofile#10]
The fwprofile source code is automatically built and linked to a library every time the master branch advances by Travis CI. However, the examples and tests which are actually included are neither built nor run.
1. update Makefile to include build instructions also for the examples and tests,
2. update .travis.yml to build examples and build / run the tests

**Comment by cechticky** [comment]
My recommendation is to add tests to the main fwprofile project, but any fwprofile example shall be a dedicated Github project. The naming convention can be fwprofile-example-name.

**Comment by cechticky** [comment]
Adding the tests to the main project allows us to extend Travis CI with running and reporting code coverage. There is Github tool supporting it out of the box. What is your opinion?

**Comment by oppm** [comment]
I wanted to split the examples for the source/tests also. I would probably have only one project fwprofile-examples containing all the examples instead of a single project for each example. Firstly, the examples are reasonably small and secondly, you get quite a few projects otherwise.

You mean, to include/connect a GitHub tool to visualize the gcov coverage output, right ? Not writing the tests in another tool, correct ? If yes, then I think it makes definitely sense to add this.

**Comment by cechticky** [comment]
Yes, one project just with examples would be sufficient. Just please bear in mind that every example is an executable that needs to be executed and its output validated. And, every example has documentation done with doxygen.

There is something available for gcov coverage visualisation for Github. Please, take a bit time searching for it.

Last but not least, we should make the Github repo for fwprofile such that the next release can be done with Github release concept. We have been using a custom scripts so far. To be frank, we should get rid of this concept. The same approach can be then used for CORDET framework as well.

**Comment by oppm** [comment]
I created a new project fwprofile-examples and added the examples source files there. I also created a Makefile to build and run them. It works well. Please have a look. If ok, I will remove the examples stuff from this branch (and also investigate on coverage visualisation).

**Comment by cechticky** [comment]
Great, may be have a look at this:
https://github.com/integrations/coveralls
https://github.com/integrations/codecov
Many thanks Va.

**Comment by oppm** [comment]
Ok, I finally managed to get codecov running. Coveralls did not work, I don't know why... Anyway, check it out under: 
https://codecov.io/gh/pnp-software/fwprofile
