### ISSUE TITLE
Comment about Dead Code in CrFwAux

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fwprofile#13]
Feedback from ESA after execution of static code analysis. 

Dead code has been found in module CrFwAux. The finding is correct but this module implements a generic consistency check for the framework data structures. Since the check is generic, it may contain dead code for some specific instantiation of the framework. Also, as explained in its docygen documentation, this module is not intended to be included in the final application executable.

To facilitate future runs of the static code analyzer, we will add a comment in the source code of the following kind: `// The following can be dead code, depending on the specific instantiation of the FW Profile.`

**Comment by oppm** [comment]
I think this issue should be on the cordet fw and not on framework profile, right ?

**Comment by pasetti** [comment]
Yes, it should be in the CORDET  Project. Please move it there.

**Comment by oppm** [comment]
Moved issue to CORDET project.
