### ISSUE TITLE
Error in Doxygen Comment of Function FwPrGetCurNode

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fwprofile#5]
The doxygen comment for the  FwPrGetCurNode function includes the following statement: "If the procedure is in the STARTED state but has not yet executed the any action (because the guard from the initial node is still false), this function returns -1". This should be changed to: "If the procedure is in the STARTED state but has not yet executed the any action (either because it has not yet been executed or because it has been executed but the guard from the initial node is false), this function returns -1".

**Comment by cechticky** [comment]
Issue is fixed and committed in master.
