### ISSUE TITLE
Order of Operations in Transition Execution

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fwprofile#6]
Figure 8 of the FW Profile Definition Document defines the behaviour to perform a transition in a state machine. According to the figure, when the transition is a state, then the Current State is updated and then its execution counter is reset. The implementation of this logic in function ExecTrans in module FwSmCore performs these two operations in the opposite order. As far as I can tell, this has no impact on the externally visible behaviour of a state machine but, for consistency with the design, the order of the two operations should be inverted.

**Comment by cechticky** [comment]
Issue is fixed and committed in master.
