### ISSUE TITLE
Double Execution of Procedure Guard

### ISSUE THREAD

**Issue by pasetti** [pnp-software/fwprofile#7]
With certain node topologies, it may happen that, as part of the same execution of a procedure, the same guard is evaluated twice. This should not have any consequence because guards are required to be free of side-effects but it might be inefficient and it makes the validation of the behaviour shown in figure 4 of the FW Profile Definition Document harder. For these reasons, I should consider changing the implementation of function FwPrExecute in module FwPrCore to avoid the double call and to be easier to map to the behaviour of figure 4.

**Comment by cechticky** [comment]
Issue is fixed and committed in master.
